esphome:
  name: haierac
  platform: ESP8266
  board: esp12e
  includes:
    - Haier.h

status_led:
  pin: GPIO16

wifi:
  ssid: ""
  password: ""

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ""
    password: ""

captive_portal:

time:
  - platform: sntp
    id: sntp_time
    timezone: "Europe/Warsaw"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

climate:
  - platform: custom
    lambda: |-
      auto haier = new Haier();
      App.register_component(haier);
      return {haier};
    climates:
      - name: "Haier"